### ISSUE TITLE
Dependabot PR spam

### ISSUE THREAD

**Issue by kuhnroyal** [technote-space/assign-author#255]
## Describe the bug: バグの概要
The action currently spams dependabot PRs for every test tag.

I keep getting something like this:
```
Bumps [technote-space/assign-author](https://github.com/technote-space/assign-author) from 1.6.0 to 1.6.1.2937857667.
```

This is not a release and I am not sure why the PR is being created.
Maybe related to 1.6.0 also not being a published to the marketplace. Latest version on the marketplace is 1.3.1

**Comment by technote-space** [comment]
Please report to dependabot
